// מאגר השרשראות המאוחד.
// c1–c17: מתוך games/chain/ChainItHebrew.jsx (כמו שהם).
// chain_xxx: מתוך games/chain/LovableUpdate_ChainGame.md, עם התיקונים הבאים:
//   - נוספו displayWord חסרים: chain_005 (תורה→תורת, חיים→חיי), chain_012/013 (טובה→טובת), chain_014 (חיים→חיי)
//   - chain_012: הכיתוב "ראש שנה" תוקן ל"ראש השנה"
//   - chain_006: הכיתוב "עולם התחתון" תוקן ל"העולם התחתון"
//   - הוסרו chain_001, chain_007, chain_009 כי הן חלק מתוך c1, c3, c4 (אותה שרשרת, קצרה יותר).
//
// כללי העריכה המלאים (word / link / displayWord) מתועדים בהערה הארוכה ב-ChainItHebrew.jsx.
// מדיניות אורך: 5 עד 10 מילים בשרשרת.
export const CHAINS = [
  { id: 'c1', difficulty: 'קל', theme: 'ערב שבת ותורה', words: [
      { word: 'נר',    given: true },
      { word: 'שבת',   link: 'נר שבת' },
      { word: 'שלום',  link: 'שבת שלום' },
      { word: 'בית',   link: 'שלום בית' },
      { word: 'ספר',   link: 'בית ספר' },
      { word: 'תורה',  link: 'ספר תורה' },
      { word: 'שבכתב', link: 'תורה שבכתב' },
  ]},
  { id: 'c2', difficulty: 'קל', theme: 'מזמן לתור', words: [
      { word: 'שעון', given: true },
      { word: 'חול',  link: 'שעון חול' },
      { word: 'ים',   link: 'חול ים' },
      { word: 'סוף',  link: 'ים סוף' },
      { word: 'שבוע', link: 'סוף שבוע' },
      { word: 'הבא',  link: 'שבוע הבא' },
      { word: 'בתור', link: 'הבא בתור' },
  ]},
  { id: 'c3', difficulty: 'בינוני', theme: 'מהבנק אל הרוחות', words: [
      { word: 'מספר',  given: true },
      { word: 'חשבון', link: 'מספר חשבון' },
      { word: 'בנק',   link: 'חשבון בנק' },
      { word: 'דם',    link: 'בנק דם' },
      { word: 'קר',    link: 'דם קר' },
      { word: 'רוח',   link: 'קר רוח' },
      { word: 'רפאים', link: 'רוח רפאים' },
  ]},
  { id: 'c4', difficulty: 'קשה', theme: 'מהחזר קרן ועד עד מדינה', words: [
      { word: 'החזר',  given: true },
      { word: 'קרן',   link: 'החזר קרן' },
      { word: 'אור',   link: 'קרן אור' },
      { word: 'ירוק',  link: 'אור ירוק' },
      { word: 'עד',    link: 'ירוק עד' },
      { word: 'מדינה', link: 'עד מדינה', displayWord: 'מדינת' },
      { word: 'ישראל', link: 'מדינת ישראל' },
  ]},
  { id: 'c5', difficulty: 'בינוני', theme: 'מלב זהב לביצה קשה', words: [
      { word: 'תשומת', given: true },
      { word: 'לב',    link: 'תשומת לב' },
      { word: 'זהב',   link: 'לב זהב' },
      { word: 'שחור',  link: 'זהב שחור' },
      { word: 'לבן',   link: 'שחור לבן' },
      { word: 'ביצה',  link: 'לבן ביצה' },
      { word: 'קשה',   link: 'ביצה קשה' },
  ]},
  { id: 'c6', difficulty: 'בינוני', theme: 'מעוגה למלון בוטיק', words: [
      { word: 'עוגת',   given: true },
      { word: 'שוקולד', link: 'עוגת שוקולד' },
      { word: 'חלב',    link: 'שוקולד חלב' },
      { word: 'אם',     link: 'חלב אם' },
      { word: 'בית',    link: 'אם בית' },
      { word: 'מלון',   link: 'בית מלון' },
      { word: 'בוטיק',  link: 'מלון בוטיק' },
  ]},
  { id: 'c7', difficulty: 'בינוני', theme: 'מגן חיות ללב זהב', words: [
      { word: 'גן',    given: true },
      { word: 'חיות',  link: 'גן חיות' },
      { word: 'בר',    link: 'חיות בר' },
      { word: 'מזל',   link: 'בר מזל' },
      { word: 'טוב',   link: 'מזל טוב' },
      { word: 'לב',    link: 'טוב לב' },
      { word: 'זהב',   link: 'לב זהב' },
  ]},
  { id: 'c8', difficulty: 'בינוני', theme: 'מכאב ראש לאבן חן', words: [
      { word: 'כאב',  given: true },
      { word: 'ראש',  link: 'כאב ראש' },
      { word: 'חודש', link: 'ראש חודש' },
      { word: 'טוב',  link: 'חודש טוב' },
      { word: 'לב',   link: 'טוב לב' },
      { word: 'אבן',  link: 'לב אבן' },
      { word: 'חן',   link: 'אבן חן' },
  ]},
  { id: 'c9', difficulty: 'קשה', theme: 'משינויי אקלים לחיים טובים', words: [
      { word: 'שינויי', given: true },
      { word: 'אקלים',  link: 'שינויי אקלים' },
      { word: 'חם',     link: 'אקלים חם' },
      { word: 'מזג',    link: 'חם מזג' },
      { word: 'אוויר',  link: 'מזג אוויר' },
      { word: 'קר',     link: 'אוויר קר' },
      { word: 'רוח',    link: 'קר רוח' },
      { word: 'חיים',   link: 'רוח חיים' },
      { word: 'טובים',  link: 'חיים טובים' },
  ]},
  { id: 'c10', difficulty: 'קל', theme: 'מכל יום ללב שבור', words: [
      { word: 'כל',    given: true },
      { word: 'יום',   link: 'כל יום' },
      { word: 'טוב',   link: 'יום טוב' },
      { word: 'לב',    link: 'טוב לב' },
      { word: 'שבור',  link: 'לב שבור' },
  ]},
  { id: 'c11', difficulty: 'בינוני', theme: 'מכאב ראש לאחדות לאומית', words: [
      { word: 'כאב',      given: true },
      { word: 'ראש',      link: 'כאב ראש' },
      { word: 'ממשלה',    link: 'ראש ממשלה', displayWord: 'ממשלת' },
      { word: 'אחדות',    link: 'ממשלת אחדות' },
      { word: 'לאומית',   link: 'אחדות לאומית' },
  ]},
  { id: 'c12', difficulty: 'בינוני', theme: 'מהערכת מצב לקרב מגע', words: [
      { word: 'הערכת', given: true },
      { word: 'מצב',   link: 'הערכת מצב' },
      { word: 'רוח',   link: 'מצב רוח' },
      { word: 'קרב',   link: 'רוח קרב' },
      { word: 'מגע',   link: 'קרב מגע' },
  ]},
  { id: 'c13', difficulty: 'קל', theme: 'מבית ספר לנהיגה בטוחה', words: [
      { word: 'בית',    given: true },
      { word: 'ספר',    link: 'בית ספר' },
      { word: 'לימוד',  link: 'ספר לימוד', displayWord: 'לימודי' },
      { word: 'נהיגה',  link: 'לימודי נהיגה' },
      { word: 'בטוחה',  link: 'נהיגה בטוחה' },
  ]},
  { id: 'c14', difficulty: 'בינוני', theme: 'מלחץ אוויר לרוח גבית', words: [
      { word: 'לחץ',   given: true },
      { word: 'אוויר', link: 'לחץ אוויר' },
      { word: 'קר',    link: 'אוויר קר' },
      { word: 'רוח',   link: 'קר רוח' },
      { word: 'גבית',  link: 'רוח גבית' },
  ]},
  { id: 'c15', difficulty: 'בינוני', theme: 'מכרטיס ביקור למלון בוטיק', words: [
      { word: 'כרטיס', given: true },
      { word: 'ביקור', link: 'כרטיס ביקור' },
      { word: 'בית',   link: 'ביקור בית' },
      { word: 'מלון',  link: 'בית מלון' },
      { word: 'בוטיק', link: 'מלון בוטיק' },
  ]},
  { id: 'c16', difficulty: 'קשה', theme: 'מכרטיס טיסה ללבן בוהק', words: [
      { word: 'כרטיס', given: true },
      { word: 'טיסה',  link: 'כרטיס טיסה', displayWord: 'טיסת' },
      { word: 'לילה',  link: 'טיסת לילה' },
      { word: 'טוב',   link: 'לילה טוב' },
      { word: 'לב',    link: 'טוב לב' },
      { word: 'זהב',   link: 'לב זהב' },
      { word: 'שחור',  link: 'זהב שחור' },
      { word: 'לבן',   link: 'שחור לבן' },
      { word: 'בוהק',  link: 'לבן בוהק' },
  ]},
  { id: 'c17', difficulty: 'קשה', theme: 'מרחוב ראשי לימין ושמאל', words: [
      { word: 'רחוב',    given: true },
      { word: 'ראשי',    link: 'רחוב ראשי' },
      { word: 'ממשלה',   link: 'ראשי ממשלה', displayWord: 'ממשלת' },
      { word: 'ימין',    link: 'ממשלת ימין' },
      { word: 'שמאל',    link: 'ימין שמאל' },
  ]},
  { id: 'chain_002', difficulty: 'קל', theme: 'מזל טוב', words: [
      { word: 'בר', given: true },
      { word: 'מזל', link: 'בר מזל' },
      { word: 'טוב', link: 'מזל טוב' },
      { word: 'לב', link: 'טוב לב' },
      { word: 'זהב', link: 'לב זהב' },
      { word: 'שחור', link: 'זהב שחור' },
  ]},
  { id: 'chain_003', difficulty: 'קל', theme: 'דרך ארץ', words: [
      { word: 'לילה', given: true },
      { word: 'טוב', link: 'לילה טוב' },
      { word: 'לב', link: 'טוב לב' },
      { word: 'אבן', link: 'לב אבן' },
      { word: 'דרך', link: 'אבן דרך' },
      { word: 'ארץ', link: 'דרך ארץ' },
  ]},
  { id: 'chain_004', difficulty: 'קל', theme: 'סוף שבוע', words: [
      { word: 'טוב', given: true },
      { word: 'לב', link: 'טוב לב' },
      { word: 'ים', link: 'לב ים' },
      { word: 'סוף', link: 'ים סוף' },
      { word: 'שבוע', link: 'סוף שבוע' },
      { word: 'הבא', link: 'שבוע הבא' },
  ]},
  { id: 'chain_005', difficulty: 'בינוני', theme: 'בית דין', words: [
      { word: 'בית', given: true },
      { word: 'דין', link: 'בית דין' },
      { word: 'תורה', link: 'דין תורה', displayWord: 'תורת' },
      { word: 'חיים', link: 'תורת חיים', displayWord: 'חיי' },
      { word: 'לילה', link: 'חיי לילה' },
      { word: 'טוב', link: 'לילה טוב' },
  ]},
  { id: 'chain_006', difficulty: 'בינוני', theme: 'זמן וים', words: [
      { word: 'שעון', given: true },
      { word: 'חול', link: 'שעון חול' },
      { word: 'ים', link: 'חול ים' },
      { word: 'סוף', link: 'ים סוף' },
      { word: 'עולם', link: 'סוף עולם' },
      { word: 'התחתון', link: 'העולם התחתון' },
  ]},
  { id: 'chain_008', difficulty: 'בינוני', theme: 'מטבח', words: [
      { word: 'עוגת', given: true },
      { word: 'שוקולד', link: 'עוגת שוקולד' },
      { word: 'חלב', link: 'שוקולד חלב' },
      { word: 'אם', link: 'חלב אם' },
      { word: 'בית', link: 'אם בית' },
      { word: 'ספר', link: 'בית ספר' },
  ]},
  { id: 'chain_010', difficulty: 'בינוני', theme: 'צדק', words: [
      { word: 'שלום', given: true },
      { word: 'בית', link: 'שלום בית' },
      { word: 'משפט', link: 'בית משפט' },
      { word: 'צדק', link: 'משפט צדק' },
      { word: 'חברתי', link: 'צדק חברתי' },
  ]},
  { id: 'chain_011', difficulty: 'בינוני', theme: 'מלח הארץ', words: [
      { word: 'תשומת', given: true },
      { word: 'לב', link: 'תשומת לב' },
      { word: 'ים', link: 'לב ים' },
      { word: 'מלח', link: 'ים מלח' },
      { word: 'הארץ', link: 'מלח הארץ' },
  ]},
  { id: 'chain_012', difficulty: 'בינוני', theme: 'ראש השנה', words: [
      { word: 'כאב', given: true },
      { word: 'ראש', link: 'כאב ראש' },
      { word: 'שנה', link: 'ראש השנה' },
      { word: 'טובה', link: 'שנה טובה', displayWord: 'טובת' },
      { word: 'הנאה', link: 'טובת הנאה' },
  ]},
  { id: 'chain_013', difficulty: 'בינוני', theme: 'קשר עין', words: [
      { word: 'איש', given: true },
      { word: 'קשר', link: 'איש קשר' },
      { word: 'עין', link: 'קשר עין' },
      { word: 'טובה', link: 'עין טובה', displayWord: 'טובת' },
      { word: 'הנאה', link: 'טובת הנאה' },
  ]},
  { id: 'chain_014', difficulty: 'קל', theme: 'מים חיים', words: [
      { word: 'כוס', given: true },
      { word: 'מים', link: 'כוס מים' },
      { word: 'חיים', link: 'מים חיים', displayWord: 'חיי' },
      { word: 'לילה', link: 'חיי לילה' },
      { word: 'לבן', link: 'לילה לבן' },
  ]},
  { id: 'chain_015', difficulty: 'קל', theme: 'חגיגה', words: [
      { word: 'גן', given: true },
      { word: 'חיות', link: 'גן חיות' },
      { word: 'בר', link: 'חיות בר' },
      { word: 'מצווה', link: 'בר מצווה' },
      { word: 'גדולה', link: 'מצווה גדולה' },
  ]},
  { id: 'chain_016', difficulty: 'קשה', theme: 'שדה קרב', words: [
      { word: 'אם', given: true },
      { word: 'בית', link: 'אם בית' },
      { word: 'משפט', link: 'בית משפט' },
      { word: 'שדה', link: 'משפט שדה' },
      { word: 'קרב', link: 'שדה קרב' },
  ]},
  { id: 'chain_017', difficulty: 'קשה', theme: 'צדק פואטי', words: [
      { word: 'אם', given: true },
      { word: 'בית', link: 'אם בית' },
      { word: 'דין', link: 'בית דין' },
      { word: 'צדק', link: 'דין צדק' },
      { word: 'פואטי', link: 'צדק פואטי' },
  ]},
];
